-- Supabase Schema for Leads Table
-- Run this in your Supabase SQL Editor to create the leads table

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  email text not null,
  name text not null,
  company text not null,
  qualification_score integer default 0,
  status text check (status in ('new', 'contacted', 'qualified', 'converted')) default 'new',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.leads enable row level security;

-- Create policy for public read access (for demo purposes)
create policy "Public can view leads" on public.leads
  for select using (true);

-- Create policy for public insert (for demo purposes)
-- In production, you'd want to restrict this
create policy "Public can insert leads" on public.leads
  for insert with check (true);

-- Create index for faster lookups
create index if not exists leads_email_idx on public.leads (email);
create index if not exists leads_status_idx on public.leads (status);
create index if not exists leads_created_at_idx on public.leads (created_at);

-- Add comment for documentation
comment on table public.leads is 'Stores lead information from the Buzz landing page';
